// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport(arg1) {
  return window['go']['main']['App']['CancelExport'](arg1);
}

export function ConfirmCloseAck() {
  return window['go']['main']['App']['ConfirmCloseAck']();
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DetectGPU() {
  return window['go']['main']['App']['DetectGPU']();
}

export function FFmpegCheck() {
  return window['go']['main']['App']['FFmpegCheck']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function FontPath(arg1) {
  return window['go']['main']['App']['FontPath'](arg1);
}

export function ForceClose() {
  return window['go']['main']['App']['ForceClose']();
}

export function GetPrefs(arg1) {
  return window['go']['main']['App']['GetPrefs'](arg1);
}

export function MediaBase() {
  return window['go']['main']['App']['MediaBase']();
}

export function Mkdtemp(arg1) {
  return window['go']['main']['App']['Mkdtemp'](arg1);
}

export function OpenFilesDialog(arg1) {
  return window['go']['main']['App']['OpenFilesDialog'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResetGPU() {
  return window['go']['main']['App']['ResetGPU']();
}

export function ResourcesPath() {
  return window['go']['main']['App']['ResourcesPath']();
}

export function Rmdir(arg1) {
  return window['go']['main']['App']['Rmdir'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SetPrefs(arg1, arg2) {
  return window['go']['main']['App']['SetPrefs'](arg1, arg2);
}

export function StartExport(arg1) {
  return window['go']['main']['App']['StartExport'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
