// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelExport(arg1:string):Promise<void>;

export function ConfirmCloseAck():Promise<void>;

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<boolean>;

export function DetectGPU():Promise<main.GPUCaps>;

export function FFmpegCheck():Promise<main.FFmpegStatus>;

export function FileExists(arg1:string):Promise<boolean>;

export function FontPath(arg1:string):Promise<string>;

export function ForceClose():Promise<void>;

export function GetPrefs(arg1:string):Promise<any>;

export function Mkdtemp(arg1:string):Promise<string>;

export function OpenFilesDialog(arg1:string):Promise<Array<main.MediaEntry>>;

export function OpenPath(arg1:string):Promise<string>;

export function Platform():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ResetGPU():Promise<boolean>;

export function ResourcesPath():Promise<string>;

export function Rmdir(arg1:string):Promise<boolean>;

export function SaveFileDialog(arg1:string,arg2:Array<main.FileFilterInput>):Promise<string>;

export function SetPrefs(arg1:string,arg2:any):Promise<boolean>;

export function StartExport(arg1:Record<string, any>):Promise<Record<string, any>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
